version: "3.9"
services:
  mongo:
    image: mongo:6
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    env_file:
      - ./backend/.env
    environment:
      - MONGO_URI=mongodb://mongo:27017/edm
      - CORS_ORIGIN=http://localhost:5173
      - PORT=4000
    depends_on:
      - mongo
    ports:
      - "4000:4000"

  frontend:
    build: ./frontend
    environment:
      - VITE_API_BASE_URL=http://localhost:4000/api/v1
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  mongo-data:


